nodeLinker: node-modules
packageExtensions:
  astro@*:
    peerDependencies:
      typescript: "*"
      temporal-polyfill: "*"
  "@astrojs/language-server@*":
    peerDependencies:
      typescript: "*"
