nodeLinker: node-modules

packageExtensions:
  "@astrojs/language-server@*":
    peerDependencies:
      typescript: "*"
  astro@*:
    peerDependencies:
      temporal-polyfill: "*"
      typescript: "*"
