approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "@astrojs/language-server@*":
    peerDependencies:
      typescript: "*"
  astro@*:
    peerDependencies:
      temporal-polyfill: "*"
      typescript: "*"
